/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface NextflowCounter {
      'startTime': number;
    }
  }

  interface HTMLNextflowCounterElement extends StencilComponents.NextflowCounter, HTMLStencilElement {}

  var HTMLNextflowCounterElement: {
    prototype: HTMLNextflowCounterElement;
    new (): HTMLNextflowCounterElement;
  };
  interface HTMLElementTagNameMap {
    'nextflow-counter': HTMLNextflowCounterElement;
  }
  interface ElementTagNameMap {
    'nextflow-counter': HTMLNextflowCounterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'nextflow-counter': JSXElements.NextflowCounterAttributes;
    }
  }
  namespace JSXElements {
    export interface NextflowCounterAttributes extends HTMLAttributes {
      'onCounterFinished'?: (event: CustomEvent) => void;
      'startTime'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;